################################################################################
#  Spring Boot Application Deployment & Service
#  Designed and Developed by: @sak_shetty
#  Description:
#     - Deploys Spring Boot App from DockerHub public image
#     - Waits for MySQL pod readiness before startup
#     - Exposes external LoadBalancer service on NodePort 30088
################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springapp
  namespace: sak-shetty
  labels:
    app: springapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapp
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
        - name: springapp
          image: sakit333/webapp_dev:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/springdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command: ['sh', '-c', 'until nc -z mysql 3306; do echo waiting for mysql; sleep 5; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: springapp
  namespace: sak-shetty
spec:
  selector:
    app: springapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30088
  type: LoadBalancer
